### ISSUE TITLE
Building from source fails with vala 0.36.3

### ISSUE THREAD

**Issue by d3vas** [teejee2008/timeshift#7]
I'm using timeshift on arch based distros from the [AUR](https://aur.archlinux.org/packages/timeshift/).
Recently vala was updated and timeshift no longer builds:

`Gtk/ExcludeBox.vala:301.17-301.20: error: Argument 1: Cannot pass value to reference or output parameter
store.remove(item);
^^^^
Gtk/RsyncLogWindow.vala:167.4-167.22: warning: GLib.Thread.create has been deprecated since 2.32. Use new Thread<T> ()
Compilation failed: 1 error(s), 21 warning(s)
make[1]: *** [makefile:27: all] Error 1
make: *** [makefile:2: all] Error 2
/usr/bin/makepkg: line 729: logpipe: unbound variable
warning: package timeshift failed to build, skipping`

I don't know what changed by latest vala and I'm not a programmer, so I'm just reporting this here.

**Comment by pclinuxer** [comment]
Hello: 
I've used your app Timeshift in Ubuntu and Mint and now, having moved to PCLinuxOS, I've asked the maintainers to add it to the PCLinuxOS repository.

It seems that this specific issue is keeping them from doing so.

> Package deferred until a later release because:
> [tex@localhost ~]$ rpm -qa|grep vala
> vala-tools-0.36.3-1pclos2017
> vala-0.36.3-1pclos2017
> lib64vala-devel-0.36.3-1pclos2017
> lib64vala0.36_0-0.36.3-1pclos2017

I'd greatly appreciate your notifying me when it is solved.
Thanks in advance.

p.

**Comment by dimmuboy** [comment]
Same problem here. I must downgrade to vala 0.36.2 that haven't additional vala-0.26 bin

**Comment by jacobcantele** [comment]
Having this issue as well.

**Comment by teejee2008** [comment]
Fix is commited. Latest code will compile with valac-0.36
